apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
    - port:  6397
      targetPort: 6379
  selector:
    app: demo-voting-app
    name: redis-pod
